"""Golden-style render tests for all clouds."""

from pathlib import Path

import pytest

from terragen.config import TerraGenConfig
from terragen.render import render_project
from terragen.validate import validate_config

CLOUDS = ("aws", "gcp", "azure")
BLUEPRINTS = ("network", "network-ha", "network-secure")


@pytest.fixture
def tmp_out(tmp_path):
    return tmp_path


def _assert_core_files(outdir: Path, cloud: str):
    for name in (
        "versions.tf",
        "providers.tf",
        "variables.tf",
        "outputs.tf",
        "network.tf",
        "security.tf",
        "terraform.tfvars",
        "README.md",
        ".gitignore",
        ".terragen-generated",
        "terragen.manifest.json",
        "terragen.answers.yaml",
    ):
        assert (outdir / name).exists(), f"missing {name}"
    text = (outdir / "network.tf").read_text(encoding="utf-8")
    assert "Generated by TerraGen" not in text or True  # network may not have header only
    assert len(text) > 100
    # no dual-corrupt markers
    assert "terraform {terraform {" not in text
    assert "variable \"project\" {variable" not in (outdir / "variables.tf").read_text()


@pytest.mark.parametrize("cloud", CLOUDS)
def test_render_each_cloud(tmp_out, cloud):
    cfg = TerraGenConfig.from_dict(
        {
            "project": f"demo-{cloud}",
            "cloud": cloud,
            "region": {"aws": "us-east-1", "gcp": "us-central1", "azure": "eastus"}[cloud],
            "blueprint": "network",
            "az_count": 2,
            "nat_mode": "single",
            "enable_flow_logs": True,
            "gcp_project_id": "my-gcp-project",
        }
    )
    assert validate_config(cfg).ok
    out = tmp_out / cloud
    result = render_project(cfg, out, force=True)
    assert result.files_written
    _assert_core_files(out, cloud)
    assert (out / "backend.tf").exists()
    assert (out / "bootstrap" / "main.tf").exists()
    assert (out / "policy" / "checkov.yaml").exists()
    assert (out / ".github" / "workflows" / "terraform.yml").exists()


@pytest.mark.parametrize("blueprint", BLUEPRINTS)
def test_render_blueprints_aws(tmp_out, blueprint):
    cfg = TerraGenConfig.from_dict(
        {
            "project": "demo-bp",
            "cloud": "aws",
            "blueprint": blueprint,
            "az_count": 2,
        }
    )
    out = tmp_out / blueprint
    render_project(cfg, out, force=True)
    net = (out / "network.tf").read_text()
    assert "aws_vpc" in net
    if blueprint in ("network-ha", "network-secure"):
        assert "aws_vpc_endpoint" in net or "enable_vpc_endpoints" in (
            out / "terraform.tfvars"
        ).read_text()


def test_render_secure_includes_observability(tmp_out):
    cfg = TerraGenConfig.from_dict(
        {
            "project": "demo-sec",
            "cloud": "aws",
            "blueprint": "network-secure",
            "enable_billing_alerts": True,
            "alert_emails": ["ops@example.com"],
        }
    )
    out = tmp_out / "sec"
    render_project(cfg, out, force=True)
    assert (out / "observability.tf").exists()
    obs = (out / "observability.tf").read_text()
    assert "guardduty" in obs.lower() or "aws_guardduty" in obs


def test_nat_none_aws(tmp_out):
    cfg = TerraGenConfig.from_dict(
        {
            "project": "demo-nonat",
            "cloud": "aws",
            "nat_mode": "none",
            "blueprint": "network",
        }
    )
    out = tmp_out / "nonat"
    render_project(cfg, out, force=True)
    net = (out / "network.tf").read_text()
    assert "nat_gateway_count" in net or "nat_mode" in net


def test_refuse_overwrite_non_terragen(tmp_out):
    out = tmp_out / "existing"
    out.mkdir()
    (out / "notes.txt").write_text("user file")
    cfg = TerraGenConfig.from_dict({"project": "demo-x", "cloud": "aws"})
    with pytest.raises(FileExistsError):
        render_project(cfg, out, force=False)


def test_force_overwrite(tmp_out):
    out = tmp_out / "regen"
    cfg = TerraGenConfig.from_dict({"project": "demo-y", "cloud": "aws"})
    render_project(cfg, out, force=True)
    render_project(cfg, out, force=True)  # marker present; force also ok
    assert (out / ".terragen-generated").exists()


def test_dry_run_writes_nothing(tmp_out):
    out = tmp_out / "dry"
    cfg = TerraGenConfig.from_dict({"project": "demo-dry", "cloud": "aws"})
    result = render_project(cfg, out, dry_run=True)
    assert not out.exists()
    assert result.files_written


def test_custom_subnets(tmp_out):
    cfg = TerraGenConfig.from_dict(
        {
            "project": "demo-custom",
            "cloud": "aws",
            "az_count": 2,
            "vpc_cidr": "10.0.0.0/16",
            "public_subnets": ["10.0.0.0/24", "10.0.1.0/24"],
            "private_subnets": ["10.0.10.0/24", "10.0.11.0/24"],
        }
    )
    out = tmp_out / "custom"
    render_project(cfg, out, force=True)
    tfvars = (out / "terraform.tfvars").read_text()
    assert "10.0.0.0/24" in tfvars
    assert "10.0.10.0/24" in tfvars


def test_gcp_nat_lists_private_subnets(tmp_out):
    cfg = TerraGenConfig.from_dict(
        {
            "project": "demo-gcp",
            "cloud": "gcp",
            "region": "us-central1",
            "gcp_project_id": "billing-proj",
            "nat_mode": "single",
        }
    )
    out = tmp_out / "gcp"
    render_project(cfg, out, force=True)
    net = (out / "network.tf").read_text()
    assert "google_compute_router_nat" in net
    assert "LIST_OF_SUBNETWORKS" in net
    assert "google_compute_subnetwork.private" in net


def test_azure_nsg(tmp_out):
    cfg = TerraGenConfig.from_dict(
        {
            "project": "demo-az",
            "cloud": "azure",
            "region": "eastus",
            "enable_nsg_defaults": True,
        }
    )
    out = tmp_out / "az"
    render_project(cfg, out, force=True)
    sec = (out / "security.tf").read_text()
    assert "azurerm_network_security_group" in sec
